version: '3.8'

services:
  langraph-app:
    build: .
    container_name: langraph-app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # For running the main application
    command: npm start
    
   